### ISSUE TITLE
DaisyDiff adding html code which has not changed as well in daisydiff.htm

### ISSUE THREAD

**Issue by kernelfreak** [DaisyDiff/DaisyDiff#3]
Hello friends,

I have added the DaisyDIff library on our system, which I am calling from command line for comparing two html files. Currently, it's working quite good. The only problem we are facing is, when there is no change in the two html files, or part of it remains same, then also it is added in the diff report. How can I exclude this? Any ideas. Thank you.

**Comment by ataillefer** [comment]
That's the way DaisyDiff works, it will always generate a report with the content of the given files including annotations about the differences if any.
If the 2 files are identical you'll get the raw content inside the report.
